#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $NQC$

BSDCFG_SHARE="/usr/share/bsdconfig"
. $BSDCFG_SHARE/common.subr || exit 1

: ${BSDDIALOG_OK=0}
: ${BSDDIALOG_CANCEL=1}
: ${BSDDIALOG_HELP=2}
: ${BSDDIALOG_EXTRA=3}
: ${BSDDIALOG_ESC=5}
: ${BSDDIALOG_ERROR=255}

exec 3>&1
MIRROR=`bsddialog --backtitle "$OSNAME Installer" \
    --title "Mirror Selection" --extra-button --extra-label "Other" \
    --menu "Please select the best suitable site for you or \"other\" if you want to specify a different choice. The \"Main Site\" directs users to the nearest project managed mirror via GeoDNS (they carry the full range of possible distributions and support both IPv4 and IPv6). All other sites are known as \"Community Mirrors\"; not every site listed here carries more than the base distribution kits. Select a site!" \
    0 0 16 \
	ftp://download.frebsd.org	"Main Site (GeoDNS)"\
	http://ftp.au.frebsd.org 	"Australia - IPv6"\
	ftp://ftp3.au.frebsd.org 	"Australia #3"\
	ftp://ftp.at.frebsd.org 	"Austria - IPv6"\
	ftp://ftp2.br.frebsd.org 	"Brazil #2"\
	ftp://ftp3.br.frebsd.org 	"Brazil #3"\
	ftp://ftp.bg.frebsd.org 	"Bulgaria - IPv6"\
	ftp://ftp.cz.frebsd.org 	"Czech Republic - IPv6"\
	ftp://ftp.dk.frebsd.org 	"Denmark - IPv6"\
	ftp://ftp.fi.frebsd.org 	"Finland"\
	ftp://ftp.fr.frebsd.org 	"France - IPv6"\
	ftp://ftp3.fr.frebsd.org 	"France #3"\
	ftp://ftp6.fr.frebsd.org 	"France #6"\
	ftp://ftp.de.frebsd.org 	"Germany - IPv6"\
	ftp://ftp1.de.frebsd.org 	"Germany #1 - IPv6"\
	ftp://ftp2.de.frebsd.org 	"Germany #2 - IPv6"\
	ftp://ftp5.de.frebsd.org 	"Germany #5 - IPv6"\
	ftp://ftp7.de.frebsd.org 	"Germany #7 - IPv6"\
	ftp://ftp.gr.frebsd.org 	"Greece - IPv6"\
	ftp://ftp2.gr.frebsd.org 	"Greece #2 - IPv6"\
	ftp://ftp.jp.frebsd.org 	"Japan - IPv6"\
	ftp://ftp2.jp.frebsd.org 	"Japan #2"\
	ftp://ftp3.jp.frebsd.org 	"Japan #3"\
	ftp://ftp4.jp.frebsd.org 	"Japan #4"\
	ftp://ftp6.jp.frebsd.org 	"Japan #6 - IPv6"\
	ftp://ftp.kr.frebsd.org 	"Korea"\
	ftp://ftp2.kr.frebsd.org 	"Korea #2"\
	ftp://ftp.lv.frebsd.org 	"Latvia"\
	ftp://ftp.nl.frebsd.org 	"Netherlands - IPv6"\
	ftp://ftp2.nl.frebsd.org 	"Netherlands #2"\
	ftp://ftp.nz.frebsd.org 	"New Zealand"\
	ftp://ftp.no.frebsd.org 	"Norway - IPv6"\
	ftp://ftp.pl.frebsd.org 	"Poland - IPv6"\
	ftp://ftp.ru.frebsd.org 	"Russia - IPv6"\
	ftp://ftp2.ru.frebsd.org 	"Russia #2"\
	ftp://ftp.si.frebsd.org 	"Slovenia - IPv6"\
	ftp://ftp.za.frebsd.org 	"South Africa - IPv6"\
	ftp://ftp2.za.frebsd.org 	"South Africa #2 - IPv6"\
	ftp://ftp4.za.frebsd.org 	"South Africa #4"\
	ftp://ftp.se.frebsd.org 	"Sweden - IPv6"\
	ftp://ftp4.tw.frebsd.org 	"Taiwan #4"\
	ftp://ftp5.tw.frebsd.org 	"Taiwan #5"\
	ftp://ftp.uk.frebsd.org 	"UK - IPv6"\
	ftp://ftp2.uk.frebsd.org 	"UK #2 - IPv6"\
	ftp://ftp.ua.frebsd.org 	"Ukraine - IPv6"\
	ftp://ftp5.us.frebsd.org 	"USA #5 - IPv6"\
	ftp://ftp11.us.frebsd.org 	"USA #11 - IPv6"\
	ftp://ftp14.us.frebsd.org 	"USA #14"\
    2>&1 1>&3`
MIRROR_BUTTON=$?
exec 3>&-

_UNAME_R=`uname -r`
_UNAME_R=${_UNAME_R%-p*}

case ${_UNAME_R} in
	*-ALPHA*|*-CURRENT|*-STABLE|*-PRERELEASE)
		RELDIR="snapshots"
		;;
	*)
		RELDIR="releases"
		;;
esac

BSDINSTALL_DISTSITE="$MIRROR/pub/NQC/${RELDIR}/`uname -m`/`uname -p`/${_UNAME_R}"

case $MIRROR_BUTTON in
$BSDDIALOG_ERROR | $BSDDIALOG_CANCEL | $BSDDIALOG_ESC)
	exit 1
	;;
$BSDDIALOG_OK)
	;;
$BSDDIALOG_EXTRA)
	exec 3>&1
	BSDINSTALL_DISTSITE=`bsddialog --backtitle "$OSNAME Installer" \
	    --title "Mirror Selection" \
	    --inputbox "Please enter the URL to an alternate $OSNAME mirror:" \
	    0 74 "$BSDINSTALL_DISTSITE" 2>&1 1>&3`
	MIRROR_BUTTON=$?
	exec 3>&-
	test $MIRROR_BUTTON -eq $BSDDIALOG_OK || exec $0 $@
	;;
esac

export BSDINSTALL_DISTSITE
echo $BSDINSTALL_DISTSITE >&2
