#	From: @(#)Makefile	6.3 (Berkeley) 6/8/93
# $NQC$

VOLUME=		papers
DOC=		diskperf
SRCS=		abs.ms motivation.ms equip.ms methodology.ms tests.ms \
		results.ms conclusions.ms appendix.ms
MACROS=		-ms
USE_TBL=

.include <bsd.doc.mk>
